scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chess-vlg.herokuapp.com']
#      - targets: ['host.docker.internal:8080']