version: '3.9'

services:
  app:
    build: ./
    container_name: chess_app
    depends_on:
      - postgres
    ports:
      - '10050:10050'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chess-vlg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:14.5-alpine'
    container_name: postgres_chess
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=chess-vlg
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
