server:
  port: 10050

spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chess-vlg}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: WARN
    com.example.chessvolgograd: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

service:
  url-path-classic: https://ratings.ruchess.ru/api/smanager_standard.csv.zip
  url-path-rapid: https://ratings.ruchess.ru/api/smanager_rapid.csv.zip
  url-path-blitz: https://ratings.ruchess.ru/api/smanager_blitz.csv.zip
  region: 34
  username: admin
  password: admin+admin=2*admin

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

